function(add_ucp_test target source)
    add_executable(${target} ${source})
    target_link_libraries(${target} PRIVATE proactor_static pthread)
    target_include_directories(${target} PRIVATE ${PROJECT_SOURCE_DIR}/tests)
    add_test(NAME ${target} COMMAND ${target})
endfunction()

add_ucp_test(ucp_result_test result_test.cpp)
add_ucp_test(ucp_task_test task_test.cpp)
add_ucp_test(ucp_io_operation_test io_operation_test.cpp)
add_ucp_test(ucp_event_loop_operation_test event_loop_operation_test.cpp)
add_ucp_test(ucp_async_socket_test async_socket_test.cpp)
add_ucp_test(ucp_async_connect_test async_connect_test.cpp)
