option(UCP_ENABLE_SANITIZERS "Enable AddressSanitizer and UBSan" OFF)
option(UCP_ENABLE_TSAN "Enable ThreadSanitizer" OFF)
if(UCP_ENABLE_SANITIZERS AND UCP_ENABLE_TSAN)
    message(FATAL_ERROR "ASan/UBSan and TSan must use separate build trees")
endif()
if(UCP_ENABLE_SANITIZERS AND CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    add_compile_options(-fsanitize=address,undefined -fno-omit-frame-pointer)
    add_link_options(-fsanitize=address,undefined)
endif()
if(UCP_ENABLE_TSAN AND CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    add_compile_options(-fsanitize=thread -fno-omit-frame-pointer)
    add_link_options(-fsanitize=thread)
endif()
